#goal is to check if my python code is syntactically correct

name: code lint

on:
  push:

jobs:
  code-linter-test:
    strategy:
        matrix:
          python-versions: ['3.12','3.13','3.14']
    runs-on: ubuntu-latest

    steps:
      - name: code checkout
        uses: actions/checkout@v7

      - name: setup python
        uses: actions/setup-python@v7
        with:
          python-versions: ${{matrix.python-versions}}

      - name: install dependencies
        run: pip install -r requirements.txt

      - name: code lint
        run: ruff check .

      - name: code test
        run: pytest
